[package]
name = "clock-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitblt = { path = "../bitblt" }
stencil = { path = "../stencil" }
sdlstate = { path = "../sdlstate" }
sdl2 = "0.35.2"
